services:

  postgres:
    image: postgres:16
    container_name: postgres-xa
    environment:
      POSTGRES_DB: swift_ref
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "max_prepared_transactions=100"

  artemis:
    image: apache/activemq-artemis:latest
    container_name: artemis-xa
    security_opt:
      - seccomp:unconfined
    environment:
      ARTEMIS_USER: artemis
      ARTEMIS_PASSWORD: artemis
      ANONYMOUS_LOGIN: "false"
    ports:
      - "61616:61616"
      - "8161:8161"